# Generated by Django 3.1.3 on 2020-11-25 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(default='avatars/guest.png', upload_to='D:\\website\\MatchAndMake\\media'),
        ),
    ]
