# Generated by Django 3.1.3 on 2020-11-25 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofiles', '0003_auto_20201125_1404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(default='avatars/guest.png', upload_to='avatars'),
        ),
    ]
