# Generated by Django 3.1.3 on 2020-11-26 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofiles', '0005_profile_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='cover_image',
            field=models.ImageField(default='avatars/2_101.png', upload_to='avatars'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(default='avatars/2_101.png', upload_to='avatars'),
        ),
    ]
