# Generated by Django 3.1.3 on 2020-11-27 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofiles', '0007_auto_20201126_1944'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='cover_image',
        ),
    ]
